config/routes.rb
Roma::Application.routes.draw do
	resources :reports do
		collection do
			get :all_pending
		end
	end
	resources :pending_months
	root :to => "sessions#login"
	resources :users
	resources :memberships

	  resources :groups
	  resources :exercises do
		collection do
			get :show_exercise
		end
	  end
	  resources :categories do
		collection do
			get :show_category
		end
	  end
	  resources :attendances do  
		collection do
			get :today
			get :calendar
			get :day
		end
	  end
	  resources :routines
	  resources :rates
	  resources :payments
	  resources :members do
		collection do
			get :show_member
		end
	  end
	  resources :groups
	  resources :exercises
	  resources :categories
	  
	  resources :sessions do
		collection do
			post :authenticate
		end
	  end

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :member
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :excercises
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :category
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :member
  belongs_to :rate
end

app/models/group_member.rb
class GroupMember < ActiveRecord::Base
  belongs_to :member
  belongs_to :group
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_one :membership, :dependent=>:destroy
  has_many :attendances
  has_attached_file :photo, :styles => { :small => "95x100" }
  
  validates_attachment_presence :photo  
  validates_attachment_size :photo, :less_than => 5.megabytes  
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :member
  belongs_to :rate
  has_many :payments
  has_many :pending_months
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :membership
end

app/models/pending_month.rb
class PendingMonth < ActiveRecord::Base
	belongs_to :membership
	belongs_to :rate
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  has_many :memberships
end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/models/routine.rb
class Routine < ActiveRecord::Base
  has_many :excercise_routines
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  # GET /exercises
  # GET /exercises.xml
  def index
    @exercises = Exercise.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @exercises }
    end
  end

  # GET /exercises/1
  # GET /exercises/1.xml
  def show
    @exercise = Exercise.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @exercise }
    end
  end

  # GET /exercises/new
  # GET /exercises/new.xml
  def new
    @exercise = Exercise.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @exercise }
    end
  end

  # GET /exercises/1/edit
  def edit
    @exercise = Exercise.find(params[:id])
  end

  # POST /exercises
  # POST /exercises.xml
  def create
    @exercise = Exercise.new(params[:exercise])

    respond_to do |format|
      if @exercise.save
        flash[:notice] = 'Exercise was successfully created.'
        format.html { redirect_to(@exercise) }
        format.xml  { render :xml => @exercise, :status => :created, :location => @exercise }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @exercise.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /exercises/1
  # PUT /exercises/1.xml
  def update
    @exercise = Exercise.find(params[:id])

    respond_to do |format|
      if @exercise.update_attributes(params[:exercise])
        flash[:notice] = 'Exercise was successfully updated.'
        format.html { redirect_to(@exercise) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @exercise.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.xml
  def destroy
    @exercise = Exercise.find(params[:id])
    @exercise.destroy

    respond_to do |format|
      format.html { redirect_to(exercises_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/exercises/_form.html.erb
<table align="center" class="form_table" width='100%'>
	<tr>		
 		<th><%= f.label 'Categoria:' %></th>
		<td><%= f.text_field :name, :class => "capitalize_me" %></td>
	</tr>
</table>

app/views/exercises/_new.html.erb
<div id='popup'>
	<div id='popup_info'
		<% form_for @exercise do |f| %>  
			<%= f.error_messages %>
			<%= render :partial => 'form', :locals => {:f => f} %>
		<% end %>
	</div>
</div>

app/views/exercises/edit.html.erb
<h1>Editing exercise</h1>

<% form_for(@exercise) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @exercise %> |
<%= link_to 'Back', exercises_path %>

app/views/exercises/index.html.erb
<div class='top_bar member_table_width'><span class="list_title">Listado de categorias</span></div>
<div class="table_container member_table_width">
	<table class='list_table'>
		<tr>
			<th>Id</th>
			<th>Ejercicio</th>
			<th colspan='3'>Acciones</th>
	  	</tr>

	<% @exercises.each do |exercise| %>
	  	<tr class="<%= cycle("even", "odd") %>">
			<td><%=exercise.id%></td>
			<td><%=exercise.name%> </td>
	    	<td><%= link_to 'Show', :url=>{:action=>'show_exercise', :id=>exercise.id}, {:remote=>true} %></td>
	    	<td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
	    	<td><%= link_to 'Destroy', exercise, :confirm => 'Seguro?', :method => :delete %></td>
	  	</tr>
	<% end %>
	</table>
	<div class='list_footer'>
		<%= link_to 'Agregar', :url=>{:action=>'new'}, {:class=>'link_to_new'}, {:remote=>true} %>
	</div><!--termina list footer-->
</div><!--termina list container -->	

<div id="show_exercise" style='display:none;' class='on_top' >
</div>
<div id="new_exercise" style='display:none;' class='on_top' >
</div>

<%= link_to 'New exercise', new_exercise_path %>

app/views/exercises/new.html.erb
<h1>New exercise</h1>

<% form_for(@exercise) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/show.html.erb
<%= link_to 'Edit', edit_exercise_path(@exercise) %> |
<%= link_to 'Back', exercises_path %>