config/routes.rb
Roma::Application.routes.draw do
	resources :reports do
		collection do
			get :all_pending
		end
	end
	resources :pending_months
	root :to => "sessions#login"
	resources :users
	resources :memberships

	  resources :groups
	  resources :exercises do
		collection do
			get :show_exercise
		end
	  end
	  resources :categories do
		collection do
			get :show_category
		end
	  end
	  resources :attendances do  
		collection do
			get :today
			get :calendar
			get :day
		end
	  end
	  resources :routines
	  resources :rates
	  resources :payments
	  resources :members do
		collection do
			get :show_member
		end
	  end
	  resources :groups
	  resources :exercises
	  resources :categories
	  
	  resources :sessions do
		collection do
			post :authenticate
		end
	  end

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :member
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :excercises
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :category
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :member
  belongs_to :rate
end

app/models/group_member.rb
class GroupMember < ActiveRecord::Base
  belongs_to :member
  belongs_to :group
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_one :membership, :dependent=>:destroy
  has_many :attendances
  has_attached_file :photo, :styles => { :small => "95x100" }
  
  validates_attachment_presence :photo  
  validates_attachment_size :photo, :less_than => 5.megabytes  
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :member
  belongs_to :rate
  has_many :payments
  has_many :pending_months
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :membership
end

app/models/pending_month.rb
class PendingMonth < ActiveRecord::Base
	belongs_to :membership
	belongs_to :rate
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  has_many :memberships
end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/models/routine.rb
class Routine < ActiveRecord::Base
  has_many :excercise_routines
end

app/models/routine_exercise.rb
class RoutineExercise < ActiveRecord::Base
  belongs_to :exercise
  belongs_to :routine
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  layout 'main'
  # GET /rates
  # GET /rates.xml
  def index
    @rates = Rate.all
    session[:title]='Tarifas'
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rates }
    end
  end

  # GET /rates/1
  # GET /rates/1.xml
  def show
    @rate = Rate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rate }
    end
  end

  # GET /rates/new
  # GET /rates/new.xml
  def new
    @rate = Rate.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rate }
    end
  end

  # GET /rates/1/edit
  def edit
    @rate = Rate.find(params[:id])
  end

  # POST /rates
  # POST /rates.xml
  def create
    @rate = Rate.new(params[:rate])

    respond_to do |format|
      if @rate.save
        flash[:notice] = 'Rate was successfully created.'
        format.html { redirect_to(@rate) }
        format.xml  { render :xml => @rate, :status => :created, :location => @rate }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rates/1
  # PUT /rates/1.xml
  def update
    @rate = Rate.find(params[:id])

    respond_to do |format|
      if @rate.update_attributes(params[:rate])
        flash[:notice] = 'Rate was successfully updated.'
        format.html { redirect_to(@rate) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1
  # DELETE /rates/1.xml
  def destroy
    @rate = Rate.find(params[:id])
    @rate.destroy

    respond_to do |format|
      format.html { redirect_to(rates_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rates/_form.html.erb
<table align="center" class="form_table" width='100%'>
	<tr>		
 		<th><%= f.label 'Tarifa:' %></th>
		<td><%= f.text_field :name, :class => "capitalize_me" %></td>
	</tr>
	<tr>	
	 	<th><%= f.label 'Costo:' %></th>
	   	<td><%= f.text_field :price, :class => "capitalize_me" %></td>
	</tr>
</table>

app/views/rates/edit.html.erb
<h1>Editing rate</h1>

<% form_for(@rate) do |f| %>
  <%= f.error_messages %>
	<%= render :partial => 'form', :locals => {:f => f} %>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @rate %> |
<%= link_to 'Back', rates_path %>

app/views/rates/index.html.erb
<div class='top_bar member_table_width'><span class="list_title">Listado de tarifas</span></div>
<div class="table_container member_table_width">
	<table class='list_table'>
		<tr>
			<th class='sortable'>Tarifa</th>
			<th class='sortable'>Precio</th>
			<th colspan='3'>Acciones</th>
	  	</tr>

	<% @rates.each do |rate| %>
	  	<tr class="<%= cycle("even", "odd") %>">
			<td><%=rate.name%></td>
			<td><%=number_to_currency(rate.price)%></td>
		    <td><%= link_to 'Mostrar', rate %></td>
		    <td><%= link_to 'Editar', edit_rate_path(rate) %></td>
		    <td><%= link_to 'Eliminar', rate, :confirm => 'Esta seguro?', :method => :delete %></td>
	  	</tr>
	<% end %>
	</table>
	<div class='list_footer'>
		<%= link_to 'Agregar', new_rate_path, :class=>'link_to_new' %>
	</div><!--termina list footer-->
</div><!--termina list container -->

app/views/rates/new.html.erb
<h1>New rate</h1>

<% form_for(@rate) do |f| %>
  <%= f.error_messages %>
	<%= render :partial => 'form', :locals => {:f => f} %>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', rates_path %>

app/views/rates/show.html.erb
<%= link_to 'Edit', edit_rate_path(@rate) %> |
<%= link_to 'Back', rates_path %>