config/routes.rb
Roma::Application.routes.draw do
	resources :reports do
		collection do
			get :all_pending
		end
	end
	resources :pending_months
	root :to => "sessions#login"
	resources :users
	resources :memberships

	  resources :groups
	  resources :exercises do
		collection do
			get :show_exercise
		end
	  end
	  resources :categories do
		collection do
			get :show_category
		end
	  end
	  resources :attendances do  
		collection do
			get :today
			get :calendar
			get :day
		end
	  end
	  resources :routines
	  resources :rates
	  resources :payments
	  resources :members do
		collection do
			get :show_member
		end
	  end
	  resources :groups
	  resources :exercises
	  resources :categories
	  
	  resources :sessions do
		collection do
			post :authenticate
		end
	  end

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :member
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :excercises
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :category
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :member
  belongs_to :rate
end

app/models/group_member.rb
class GroupMember < ActiveRecord::Base
  belongs_to :member
  belongs_to :group
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_one :membership, :dependent=>:destroy
  has_many :attendances
  has_attached_file :photo, :styles => { :small => "95x100" }
  
  validates_attachment_presence :photo  
  validates_attachment_size :photo, :less_than => 5.megabytes  
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :member
  belongs_to :rate
  has_many :payments
  has_many :pending_months
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :membership
end

app/models/pending_month.rb
class PendingMonth < ActiveRecord::Base
	belongs_to :membership
	belongs_to :rate
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  has_many :memberships
end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/models/routine.rb
class Routine < ActiveRecord::Base
  has_many :excercise_routines
end

app/models/routine_exercise.rb
class RoutineExercise < ActiveRecord::Base
  belongs_to :exercise
  belongs_to :routine
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # GET /reports
  # GET /reports.xml
  layout 'main'
  
  def index
    @reports = Report.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @reports }
    end
  end
  
  def all_pending
  		@pending_months = PendingMonth.all
  		@memberships = Membership.all
		    respond_to do |format|
  			format.html # show.html.erb
 		 	format.xml  { render :xml => @report }
		end
end

  # GET /reports/1
  # GET /reports/1.xml
  def show
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.xml
  def new
    @report = Report.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
  end

  # POST /reports
  # POST /reports.xml
  def create
    @report = Report.new(params[:report])

    respond_to do |format|
      if @report.save
        flash[:notice] = 'Report was successfully created.'
        format.html { redirect_to(@report) }
        format.xml  { render :xml => @report, :status => :created, :location => @report }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.xml
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        flash[:notice] = 'Report was successfully updated.'
        format.html { redirect_to(@report) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.xml
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to(reports_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reports/all_pending.html.erb
<div class='top_bar'><span class="list_title">Todos los pagos pendientes</span></div>
<div class="table_container"  >
	<table class='list_table' >
		<tr>
			<th class='sortable'>Corte</th>
			<th class='sortable'>Usuario</th>
			<th class='sortable'>Meses Pendientes</th>
			<th class='sortable'>Tarifa</th>
			<th class='sortable'>Adeudo Total</th>
			<th colspan='3'>Acciones</th>
	  	</tr>
<% @memberships.each do |membership| %>
  <tr class="<%= cycle("even", "odd") %>">
  	<td><%=membership.pay_day%> </td>
  	<td><%=membership.id%> <%=membership.member.name%> <%=membership.member.last_name%></td>
  	<td>
  		
  			<% membership.pending_months. each do |pendingMonth|%>
  				<div class='pending_month'>
  					 <%=spanish_month(pendingMonth.month)%> 
  				</div>	
  			<%end%>
  		
  	</td>
  	<td><span class='rate_price'  title='<%=membership.rate.name%> '> $<%=membership.rate.price%></td>
  	<td><%=h number_to_currency (membership.pending_months.size.to_i * membership.rate.price)%></td>
    <td><%= link_to 'Show', membership %></td>
    <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
    <td><%= link_to 'Destroy', membership, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
	<div class='list_footer'>
		<%= link_to 'Realizar un  pago', :url=>{:action=>'new'}, {:class=>'link_to_new'}, {:remote=>true}  %>
	</div><!--termina list footer-->
</div><!--termina list container -->

<div id="new_payment" style='display:none;' class='on_top' >
</div>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<% form_for(@report) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h1>Listing reports</h1>

<table>
  <tr>
  </tr>

<% @reports.each do |report| %>
  <tr>
    <td><%= link_to 'Show', report %></td>
    <td><%= link_to 'Edit', edit_report_path(report) %></td>
    <td><%= link_to 'Destroy', report, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New report', new_report_path %>

app/views/reports/new.html.erb
<h1>New report</h1>

<% form_for(@report) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>